import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { getBoxType, boxTypes } from "@/content/boxTypes";

export function generateStaticParams() { return boxTypes.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = getBoxType(slug); return { title: item?.name ?? "Box format", description: item?.description }; }
export default async function BoxDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = getBoxType(slug); if (!item) notFound(); return <div className="site-grid px-5 py-16 md:px-10 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="relative aspect-square overflow-hidden rounded-full border-2 border-ink bg-white"><Image src={item.image} alt={item.name} fill priority sizes="(max-width: 1024px) 100vw, 40vw" className="object-contain" /></div><div><div className="eyebrow">Packaging format</div><h1 className="mt-5 text-6xl md:text-8xl">{item.name}</h1><p className="mt-6 max-w-xl text-xl text-ink-soft">{item.description}</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><div className="card bg-paper p-5"><div className="mono text-xs uppercase tracking-[.12em]">Best for</div><div className="mt-2 text-xl font-bold">{item.bestFor}</div></div><div className="card bg-paper p-5"><div className="mono text-xs uppercase tracking-[.12em]">Construction</div><div className="mt-2 text-xl font-bold">{item.ply}</div></div></div><p className="mt-8 text-ink-soft">Tell us your internal dimensions, quantity and handling requirement. The quote will come back with the construction stated clearly.</p><Link href={`/quote?box=${item.slug}`} className="pill focus-ring mt-8 inline-flex bg-ultra px-7 py-4 font-bold text-paper">Quote this format ↗</Link></div></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Product", name: item.name, description: item.description, material: "Corrugated board", offers: { "@type": "AggregateOffer", priceCurrency: "INR", availability: "https://schema.org/InStock" } }) }} /></div>; }
