import Link from "next/link";
import { Faq } from "@/components/Faq";
import { HeroBoxes } from "@/components/HeroBoxes";
import { SectionIntro } from "@/components/SectionIntro";
import { BoardConstructionLoader } from "@/components/BoardConstructionLoader";

const comparison = [["Minimum order", "5,000 boxes", "500 boxes"], ["Quote turnaround", "Usually after a call", "Written in 4 working hours"], ["Written spec sheet", "Not always", "Included"], ["Pre-run sample", "Ask case by case", "Available before production"], ["Ply and GSM stated", "Sometimes", "Up front"]];
const specs = [["3 ply", "Single wall", "120-220 GSM", "<!-- UNVERIFIED -->", "Light cartons", "Retail, food and general dispatch"], ["5 ply", "Double wall", "120-220 GSM", "<!-- UNVERIFIED -->", "Medium loads", "Shipping, storage and produce"], ["7 ply", "Triple wall", "120-220 GSM", "<!-- UNVERIFIED -->", "Heavy loads", "Industrial and freight"]];

export default function Home() { return <div className="site-grid">
  <section className="mx-auto max-w-[1400px] px-5 pb-20 pt-16 text-center md:px-10 md:pt-24">
    <h1 className="mx-auto mt-6 max-w-5xl text-[clamp(3.4rem,10vw,8rem)]">Packaging built<br /><span className="text-ultra">for business.</span></h1>
    <p className="mx-auto mt-7 max-w-2xl text-lg md:text-xl">Shipping cartons, mailers, storage boxes and protective formats for procurement, warehouse and operations teams.</p>
    <div className="mt-8 flex flex-wrap items-center justify-center gap-4"><Link href="/quote" className="pill focus-ring bg-ultra px-7 py-4 font-bold text-paper">Get a quote in 4 hours <span aria-hidden="true">↗</span></Link><Link href="/boxes" className="focus-ring font-bold underline decoration-2 underline-offset-4">See what we make</Link></div>
    <div className="mono mt-10 flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs uppercase tracking-[.12em] text-ink-soft"><span>Factory direct</span><span>Written quote</span><span>Narsingi factory</span><span>Custom sizes</span></div>
    <HeroBoxes />
  </section>
  <BoardConstructionLoader />
  <section className="bg-ink px-5 py-10 text-center text-paper md:px-10"><p className="mx-auto max-w-5xl font-bold md:text-2xl">From everyday dispatch cartons to heavy-duty freight packaging. <span className="text-kraft">One factory for the full range.</span></p></section>
  <section className="mx-auto max-w-[1400px] px-5 py-20 md:px-10"><SectionIntro eyebrow="Why teams work with us" title="Packaging support that fits the way you operate." body="The right box is only useful when it arrives on time, fits the job and can be repeated on the next run." /><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="card bg-paper p-6"><div className="mono text-xs uppercase tracking-[.14em] text-ultra">Delivery planning</div><h3 className="mt-5 text-4xl">Clear dates.</h3><p className="mt-4 text-ink-soft">We plan the run around your dispatch requirement and confirm the next practical step in writing.</p></article><article className="card bg-paper p-6"><div className="mono text-xs uppercase tracking-[.14em] text-ultra">Custom solutions</div><h3 className="mt-5 text-4xl">The right format.</h3><p className="mt-4 text-ink-soft">Dimensions, ply, print, partitions and closing style are chosen around your product and handling conditions.</p></article><article className="card bg-paper p-6"><div className="mono text-xs uppercase tracking-[.14em] text-ultra">Complete line</div><h3 className="mt-5 text-4xl">One factory.</h3><p className="mt-4 text-ink-soft">Board conversion and box finishing stay close together, so questions are answered by the people running the work.</p></article></div></section>
  <section className="mx-auto max-w-[1400px] px-5 py-20 md:px-10"><SectionIntro eyebrow="Built for operations" title="Board, conversion and supply in one conversation." body="We own the machines, set the ply and make the sheets here. Your team gets a practical packaging answer, not a catalogue handoff." /><div className="mt-10 grid gap-5 md:grid-cols-[1.3fr_.7fr]"><div className="card min-h-[330px] bg-[#D7D4CB] p-6"><div className="mono text-xs uppercase tracking-[.16em]">Factory note</div><div className="mt-36 max-w-sm text-3xl font-bold">Specification starts with the board.</div></div><div className="card bg-paper p-6"><div className="eyebrow">Factory note</div><h3 className="mt-4 text-4xl">The flute carries the load.</h3><p className="mt-5 text-ink-soft">The wave between the liners gives corrugated board its strength. Tell us what the carton needs to carry and we will recommend the construction.</p></div></div></section>
  <section className="bg-ink px-5 py-20 text-paper md:px-10"><div className="mx-auto max-w-[1400px]"><SectionIntro light eyebrow="A clear comparison" title="You should not have to chase the basics." body="Here is what we put in writing before a run starts." /><div className="mt-10 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left"><thead><tr className="border-b-2 border-paper/30"><th className="p-4 font-normal text-paper/60">Question</th><th className="p-4 font-normal text-paper/60">Typical Hyderabad plant</th><th className="p-4 font-normal text-kraft">Quality Enterprises</th></tr></thead><tbody>{comparison.map(([label, other, us]) => <tr key={label} className="border-b border-paper/20"><th className="p-4 font-bold">{label}</th><td className="p-4 text-paper/70">✕ {other}</td><td className="p-4 font-bold text-kraft">✓ {us}</td></tr>)}</tbody></table></div></div></section>
  <section className="mx-auto max-w-[1400px] px-5 py-20 md:px-10"><SectionIntro eyebrow="Board specs" title="Choose the wall for the job." body="These board values are working placeholders until the machine sheet is confirmed. The final quote will state the exact construction." /><div className="mt-10 grid gap-4 md:grid-cols-3">{specs.map((row) => <div key={row[0]} className="card bg-paper p-5"><div className="mono text-xs uppercase tracking-[.14em] text-ultra">{row[0]}</div><div className="mt-5 grid gap-4">{[["Wall", row[1]], ["Liner", row[2]], ["Bursting", row[3]], ["Load", row[4]], ["Best for", row[5]]].map(([label, value]) => <div key={label}><div className="mono text-[11px] uppercase tracking-[.12em] text-ink-soft">{label}</div><div className="font-bold">{value}</div></div>)}</div></div>)}</div></section>
  <section className="bg-kraft px-5 py-20 md:px-10"><div className="mx-auto max-w-[1400px]"><SectionIntro eyebrow="Come see the line" title="A factory you can walk into." body="We are happy to show you the machines, the board and the run. The photo slots stay honest until we have the right factory images." /><div className="mt-10 grid gap-5 md:grid-cols-3">{["The corrugator", "The print line", "Finished stacks"].map((label) => <div key={label} className="card flex min-h-56 items-end bg-paper p-5"><div><div className="mono text-xs uppercase tracking-[.14em]">Photo slot</div><div className="mt-2 text-2xl font-bold">{label}</div></div></div>)}</div></div></section>
  <section className="mx-auto max-w-[1000px] px-5 py-20 md:px-10"><SectionIntro eyebrow="Questions, answered" title="Before you call." body="Short answers to the things buyers ask first." /><Faq /></section>
  <section className="bg-ultra px-5 py-16 text-paper md:px-10"><div className="mx-auto flex max-w-[1400px] flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><div className="eyebrow">Ready when you are</div><h2 className="mt-4 max-w-2xl text-5xl">Tell us what you need packed.</h2></div><Link href="/quote" className="pill focus-ring shrink-0 bg-kraft px-7 py-4 font-bold text-ink">Request a quote ↗</Link></div></section>
 </div>; }
